// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIrDS-yrIwo0z9KRk9frU1gkamJEynuxc',
    appId: '1:951239368267:web:6919878505fd432949b7ce',
    messagingSenderId: '951239368267',
    projectId: 'campus-pulse-cn',
    authDomain: 'campus-pulse-cn.firebaseapp.com',
    storageBucket: 'campus-pulse-cn.firebasestorage.app',
    measurementId: 'G-K5ZNKPTWQN',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc6NTtStldgd9O4yK4myNhKrYdfd9Ew2w',
    appId: '1:951239368267:android:9f4e8dfaf2d91a4c49b7ce',
    messagingSenderId: '951239368267',
    projectId: 'campus-pulse-cn',
    storageBucket: 'campus-pulse-cn.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtawvhP0q4vxJfAyQVZOpUA1Wy-3atgmI',
    appId: '1:951239368267:ios:72907016125de55a49b7ce',
    messagingSenderId: '951239368267',
    projectId: 'campus-pulse-cn',
    storageBucket: 'campus-pulse-cn.firebasestorage.app',
    iosBundleId: 'com.example.campusPulse',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtawvhP0q4vxJfAyQVZOpUA1Wy-3atgmI',
    appId: '1:951239368267:ios:72907016125de55a49b7ce',
    messagingSenderId: '951239368267',
    projectId: 'campus-pulse-cn',
    storageBucket: 'campus-pulse-cn.firebasestorage.app',
    iosBundleId: 'com.example.campusPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIrDS-yrIwo0z9KRk9frU1gkamJEynuxc',
    appId: '1:951239368267:web:06a5d0f388a5765f49b7ce',
    messagingSenderId: '951239368267',
    projectId: 'campus-pulse-cn',
    authDomain: 'campus-pulse-cn.firebaseapp.com',
    storageBucket: 'campus-pulse-cn.firebasestorage.app',
    measurementId: 'G-9NRGLQNHFN',
  );
}
